"""Render a research landscape to a Markdown report artifact."""

from __future__ import annotations

from researchos.core.state import ResearchState


def render_markdown(state: ResearchState) -> str:
    lines: list[str] = []
    ls = state.landscape
    lines.append(f"# Research Landscape: {state.goal}\n")
    lines.append(
        f"*Run `{state.run_id}` · project `{state.project_id}` · "
        f"{len(state.papers)} papers · {len(state.clusters)} themes*\n"
    )

    if ls and ls.summary:
        lines.append("## Summary\n")
        lines.append(ls.summary + "\n")

    if ls and ls.reading_order:
        lines.append("## Recommended reading order\n")
        for i, pid in enumerate(ls.reading_order, 1):
            p = state.papers.get(pid)
            if not p:
                continue
            star = " ⭐" if pid in ls.key_papers else ""
            authors = ", ".join(p.authors[:3]) + (" et al." if len(p.authors) > 3 else "")
            year = p.year or "n.d."
            code = ""
            if p.code_urls:
                code = " · " + ", ".join(f"[code]({u})" for u in p.code_urls[:2])
            cites = f" · {p.citation_count} citations" if p.citation_count else ""
            lines.append(
                f"{i}. **{p.title}**{star} — {authors} ({year}). "
                f"[{p.source}:{p.source_id}]({p.url}){cites}{code}"
            )
        lines.append("")

    if state.clusters:
        lines.append("## Themes\n")
        for c in state.clusters:
            lines.append(
                f"### {c.label}  \n_{len(c.paper_ids)} papers · keywords: "
                f"{', '.join(c.keywords) or 'n/a'}_\n"
            )
            for pid in c.paper_ids:
                p = state.papers.get(pid)
                if p:
                    lines.append(f"- {p.title}")
            lines.append("")

    if state.cards:
        lines.append("## Research cards\n")
        for pid in ls.key_papers if ls else list(state.cards):
            card = state.cards.get(pid)
            p = state.papers.get(pid)
            if not card or not p:
                continue
            lines.append(f"### {p.title}\n")
            lines.append(f"*card by: {card.generated_by}*\n")
            for label, value in [
                ("Problem", card.problem),
                ("Key idea", card.key_idea),
                ("Method", card.method),
                ("Results", card.results),
                ("Limitations", card.limitations),
                ("Reproduction difficulty", card.repro_difficulty),
                ("Opportunities", card.opportunities),
            ]:
                if value and value != "unknown":
                    lines.append(f"- **{label}:** {value}")
            lines.append("")

    rv = state.review
    if rv:
        lines.append("## Critic review\n")
        lines.append(f"**Score: {rv.score}/10** · _reviewed by {rv.reviewed_by}_\n")
        if rv.coverage:
            lines.append(f"- **Coverage:** {rv.coverage}")
        if rv.cluster_balance:
            lines.append(f"- **Theme balance:** {rv.cluster_balance}")
        for label, items in [
            ("Strengths", rv.strengths),
            ("Weaknesses", rv.weaknesses),
            ("Suggestions", rv.suggestions),
        ]:
            if items:
                lines.append(f"\n**{label}:**")
                lines.extend(f"- {it}" for it in items)
        if rv.missing_seminal:
            lines.append("\n**Possibly missing seminal work:**")
            lines.extend(f"- {t}" for t in rv.missing_seminal)
        lines.append("")

    if state.ideas:
        lines.append("## Research ideas (gap analysis)\n")
        for idea in state.ideas:
            lines.append(f"### {idea.title}\n")
            lines.append(
                f"*{idea.generated_by} · novelty {idea.novelty:.2f} · "
                f"feasibility {idea.feasibility:.2f}*\n"
            )
            if idea.hypothesis:
                lines.append(f"- **Hypothesis:** {idea.hypothesis}")
            if idea.rationale:
                lines.append(f"- **Rationale:** {idea.rationale}")
            if idea.gap:
                lines.append(f"- **Gap:** {idea.gap}")
            if idea.grounding:
                lines.append(f"- **Grounded in:** {', '.join(idea.grounding)}")
            lines.append("")

    lines.append("---\n*Generated by ResearchOS.*")
    return "\n".join(lines)
