"""Render a research landscape to a Markdown report artifact."""

from __future__ import annotations

from researchos.core.state import ResearchState


def render_markdown(state: ResearchState) -> str:
    lines: list[str] = []
    ls = state.landscape
    lines.append(f"# Research Landscape: {state.goal}\n")
    lines.append(
        f"*Run `{state.run_id}` · project `{state.project_id}` · "
        f"{len(state.papers)} papers · {len(state.clusters)} themes*\n"
    )

    if ls and ls.summary:
        lines.append("## Summary\n")
        lines.append(ls.summary + "\n")

    if ls and ls.reading_order:
        lines.append("## Recommended reading order\n")
        for i, pid in enumerate(ls.reading_order, 1):
            p = state.papers.get(pid)
            if not p:
                continue
            star = " ⭐" if pid in ls.key_papers else ""
            authors = ", ".join(p.authors[:3]) + (" et al." if len(p.authors) > 3 else "")
            year = p.year or "n.d."
            lines.append(
                f"{i}. **{p.title}**{star} — {authors} ({year}). "
                f"[{p.source}:{p.source_id}]({p.url})"
            )
        lines.append("")

    if state.clusters:
        lines.append("## Themes\n")
        for c in state.clusters:
            lines.append(
                f"### {c.label}  \n_{len(c.paper_ids)} papers · keywords: "
                f"{', '.join(c.keywords) or 'n/a'}_\n"
            )
            for pid in c.paper_ids:
                p = state.papers.get(pid)
                if p:
                    lines.append(f"- {p.title}")
            lines.append("")

    if state.cards:
        lines.append("## Research cards\n")
        for pid in ls.key_papers if ls else list(state.cards):
            card = state.cards.get(pid)
            p = state.papers.get(pid)
            if not card or not p:
                continue
            lines.append(f"### {p.title}\n")
            lines.append(f"*card by: {card.generated_by}*\n")
            for label, value in [
                ("Problem", card.problem),
                ("Key idea", card.key_idea),
                ("Method", card.method),
                ("Results", card.results),
                ("Limitations", card.limitations),
                ("Reproduction difficulty", card.repro_difficulty),
                ("Opportunities", card.opportunities),
            ]:
                if value and value != "unknown":
                    lines.append(f"- **{label}:** {value}")
            lines.append("")

    lines.append("---\n*Generated by ResearchOS.*")
    return "\n".join(lines)
